# Generated by Django 5.2.5 on 2025-10-25 11:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bina tam adı (Örn: Mühendislik Fakültesi A Binası)', max_length=255)),
                ('code', models.CharField(help_text='Bina kısa kodu (Örn: AS)', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Örn: Asst. Prof. Dr.', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('staff_id', models.CharField(blank=True, help_text='Personel sicil numarası', max_length=100, null=True, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='api.department')),
            ],
            options={
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_number', models.CharField(help_text='Örn: 111', max_length=50)),
                ('floor', models.IntegerField()),
                ('capacity', models.PositiveIntegerField(default=1, help_text='Oda kapasitesi')),
                ('num_desks', models.PositiveIntegerField(default=0)),
                ('num_chairs', models.PositiveIntegerField(default=0)),
                ('num_cabinets', models.PositiveIntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='api.building')),
                ('departments', models.ManyToManyField(blank=True, related_name='offices', to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Eğer personel hala bu ofisteyse bu alan boş olmalıdır.', null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.faculty')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.office')),
            ],
            options={
                'unique_together': {('faculty', 'end_date')},
            },
        ),
    ]
