# Generated by Django 5.2.2 on 2025-12-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Oda kapasitesi (Room Capacity (People))'),
        ),
        migrations.AlterField(
            model_name='office',
            name='num_cabinets',
            field=models.PositiveIntegerField(default=0, help_text='Number of Cabinets'),
        ),
        migrations.AlterField(
            model_name='office',
            name='num_chairs',
            field=models.PositiveIntegerField(default=0, help_text='Number of Chairs'),
        ),
        migrations.AlterField(
            model_name='office',
            name='num_desks',
            field=models.PositiveIntegerField(default=0, help_text='Number of Desks'),
        ),
    ]
