# Generated by Django 5.2.2 on 2025-12-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_office_capacity_alter_office_num_cabinets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='office_schedule',
            field=models.TextField(blank=True, help_text='Ofis saatleri (Pzt 10:00-12:00 vb.)', null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Örn: +90 533 123 45 67', max_length=20, null=True),
        ),
    ]
