"""
Django settings for office_management project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url  # <-- PostgreSQL bağlantısı için eklendi
import os               # <-- (Genellikle dj_database_url ile kullanılır)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Bu anahtar sana özeldir, değiştirmene gerek yok
SECRET_KEY = 'django-insecure-by==k=-d=vs4+=9v%ofw11gm(ts32^0=+x9jo)ney4=cf@efft'

# SECURITY WARNING: don't run with debug turned on in production!
# Geliştirme aşamasında 'True' kalması iyidir
DEBUG = True

# Projenizi yayınlarken buraya sitenizin adresini (domain) eklemeniz gerekecek
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Bizim uygulamalarımız en üstte olmalı
    'api.apps.ApiConfig',  # 'api' uygulamamızı tanıttık
    
    # Üçüncü parti uygulamalar
    'rest_framework',      # Django REST Framework'ü tanıttık
    
    # Django'nun kendi uygulamaları
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'office_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'office_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# ---- POSTGRESQL AYARI ----
# Burası SQLite'tan PostgreSQL'e dönüştürüldü.

# !!! ÇOK ÖNEMLİ !!!
# LÜTFEN 'postgres://...' İLE BAŞLAYAN KENDİ VERİTABANI URL'NİZİ AŞAĞIYA YAPIŞTIRIN
# BU URL'Yİ SUPABASE VEYA POSTGRESQL SAĞLAYICINIZDAN ALMALISINIZ
# ÖRNEK: 'postgres://postgres:[SIFRENIZ]@db.abc.supabase.co:5432/postgres'
DATABASE_URL = 'BURAYA_KENDİ_POSTGRESQL_URLNİZİ_YAPIŞTIRIN'


# DATABASE_URL boş değilse dj_database_url ile ayarla
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL)
    }
else:
    # URL boşsa, hata vermemesi için geçici olarak SQLite'a düşür
    print("UYARI: DATABASE_URL ayarlanmamış. Geçici olarak SQLite kullanılıyor.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Projenin dilini ve saat dilimini Türkçeye ayarlayalım
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'