"""
Django settings for office_management project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
import os
import sys  # <-- EKLENDİ: Test komutunu algılamak için gerekli

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-by==k=-d=vs4+=9v%ofw11gm(ts32^0=+x9jo)ney4=cf@efft'

DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Bizim uygulamamız
    'api.apps.ApiConfig',
    
    # Üçüncü parti uygulamalar
    'rest_framework',
    'rest_framework_simplejwt', # <-- EKLENDİ: Token authentication için gerekli
    'django_filters',           # <-- EKLENDİ: Filtreleme işlemleri için gerekli
    
    # Django'nun kendi uygulamaları
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'office_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'office_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(default=DATABASE_URL)
    }
else:
    print("UYARI: DATABASE_URL ayarlanmamış. Geçici olarak SQLite kullanılıyor.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- REST FRAMEWORK AYARLARI ---
# (İsteğe bağlı ama iyi bir pratik)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


# --- TEST AYARLARI (SON VE EN ÖNEMLİ ADIM) ---
# Test komutu çalıştırıldığında (python manage.py test) devreye girer.

if 'test' in sys.argv:
    # 1. 'api' uygulaması için Migration'ları devre dışı bırak.
    # Böylece Django, migration dosyalarına bakmak yerine 
    # modelleri (models.py) direkt okuyarak test veritabanını oluşturur.
    # Bu, 'managed=False' sorununu çözer.
    MIGRATION_MODULES = {
        'api': None,
    }
    
    # 2. Oluşturduğumuz özel Test Runner'ı kullan.
    # (Bu dosyanın 'api/test_runner.py' içinde olduğunu varsayıyoruz)
    TEST_RUNNER = 'api.test_runner.ForceManagedModelTestRunner'